name: test

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

concurrency:
  group: "bot-afk"
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    permissions:
      contents: write

    env:
      HOST: twoj-serwer.aternos.me
      PORT: 25565
      USERNAME: MojBot
      COMMAND: "/login haslo"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install mineflayer

      - name: Run
        run: |
          MAX_RESTARTS=100
          COUNT=0

          while [ $COUNT -lt $MAX_RESTARTS ]; do
            echo "Uruchamianie bota..."
            node index.js

            COUNT=$((COUNT+1))
            echo "Restart $COUNT z $MAX_RESTARTS za 30 sekund..."
            sleep 30
          done

          echo "Osiągnięto limit restartów."

      - name: Keep Workflow Active
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          echo "Last run: $(date)" > keep_alive.txt

          git add keep_alive.txt
          git commit -m "Keep-alive: Workflow heart-beat" || exit 0
          git push
